### ISSUE TITLE
Fix 'undefined' tab showing up in tabs-group after importing tabs

### ISSUE THREAD

**Issue by osBins** [osdc/TabuRei#59]
![image](https://user-images.githubusercontent.com/70942982/128629885-922435b1-0f8b-4348-a9f1-1a0d791a0601.png)

Issue is caused by cursor being in a newline when tabs are being imported.
![image](https://user-images.githubusercontent.com/70942982/128629910-e45b9b52-1ff4-47ff-bd21-b6b1bfee573c.png)

**Comment by aadishjain08** [comment]
@akshgpt7 I would like to work on this issue. I am currently unable to understand the functionality of import tabs feature. Could you please help me out so that I can take up this issue.

Thanks!

**Comment by daemon1024** [comment]
@aadishjain08 Thanks for the interest.

You can use Import Tabs feature to import any set of tabs either exported by TabuRei or by other compatible tab managers like OneTab...

This is how the exported content looks like
![image](https://user-images.githubusercontent.com/47106543/145869278-c6aabda6-9ce0-4168-b041-05cc291dda3a.png)
If you copy paste this into the Import Tabs block and then press Import and then refresh your tab manager, you should see new set of tab groups.

This is primarily added to
1. Let folks migrating from OneTab or the likes to let import ther existing tab list
2. Since it's all text you can store it somewhere for backup and import on your new instance of TabuRei or something.

Does this help?

**Comment by aadishjain08** [comment]
@daemon1024 thanks a lot for your explanation. I got your point. 
I tried the import tabs feature and faced the below attached error.
I have also tried replacing browser with chrome.browserAction ( solution suggested in stack overflow ) but wasn't able to resolve this.

Could you please help me out.
thanks!
![Screenshot (4)](https://user-images.githubusercontent.com/92850996/146006945-1f75ab36-aca1-4694-9bda-2d596eb1ef9b.png)

**Comment by daemon1024** [comment]
Hey @aadishjain08, Thanks for noticing this. I looked into it.

To give some context. We have used Firefox Browser API to make our extension and we use a compatibility polyfill to make it compatible with chrome APIs.
https://github.com/osdc/TabuRei/blob/66afb2bb5542461e534ad3e9782f4c5b3775320f/index.html#L29-L30

But we forgot to include this in import and export.html 😓 
Can you add these two lines in those HTML files? This will hopefully make it work as expected in Chrome.
Will you be up for raising an issue/PR for this?

Else you can try things out on Firefox while I fix it over the weekend.

Thank You

**Comment by aadishjain08** [comment]
@daemon1024 ,thanks a lot for your quick reply.
I would create an issue and pull request to mitigate the browser error.
And now I am able to use import and export functionality in Chrome.
Thanks again!

**Comment by daemon1024** [comment]
Great work @aadishjain08! Thank You.

Are you able to reproduce this issue?

**Comment by aadishjain08** [comment]
Yes, I am able to reproduce it.

**Comment by aadishjain08** [comment]
Hi @daemon1024 I have raised the pull request for the issue .Please verify that and let me know if any concern !
Issue59 undefined issue fixed--Pull request name.
